global:
  scrape_interval: 30s
  evaluation_interval: 30s
  # 메트릭 보존 기간 설정 (성능 최적화)
  external_labels:
    monitor: "spring-monitor"

# 메트릭 저장 최적화
rule_files: []

scrape_configs:
  - job_name: "spring-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["spring-app:80"]
    scrape_interval: 30s
    scrape_timeout: 10s
    # 메트릭 필터링 (필요한 메트릭만 수집)
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "jvm_.*|http_server_requests_.*|system_.*"
        action: keep
