spring:
  application:
    name: awktest

server:
  port: 80                # 8080 ? 80?? ??

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  metrics:
    tags:
      application: demo-app
